import blueShirt from "../assets/blue-shirt.webp";

const productsArr = [
  {
    id: 1,
    name: "bunny t-shirt",
    description: "best t-shirt in the market",
    price: 10.05,
    stock: 0,
    featuredImage: blueShirt,
    outOfStock: true,
  },
  {
    id: 2,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20.0,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 3,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 0,
    featuredImage: blueShirt,
    outOfStock: true,
  },
  {
    id: 4,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 5,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 6,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 7,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 8,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 9,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 10,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 11,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 12,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 13,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
  {
    id: 14,
    name: "polo t-shirt",
    description: "best t-shirt in the market",
    price: 20,
    stock: 50,
    featuredImage: blueShirt,
    outOfStock: false,
  },
];

export default productsArr;
